### ISSUE TITLE
MDA complexities

### ISSUE THREAD

**Issue by nr-nd** [vecnet/om#11]
> 'Coartem' would actually be called 'MDA' (mass drug administration) for which coartem is one possible drug. Coartem is a brand name, the better name would be AL or ACT.... but actually MDA is rather complicated to parameterize. On looking at this, we wondered if it might be better to remove this one altogether.

**Comment by Baguage** [comment]
Coartem is an active ingredient and can be used in different interventions potentially. Per our phone discussion, it should be removed for now
